### PR TITLE
refactor: Move out git env population from build.rs to shared crate

### PR DESCRIPTION
**Pull request by netrome**

### CODE REVIEW

**Review by donpdonp — CHANGES_REQUESTED** [review]
This all looks good though I would like to see the body of main() remain as it shows what env variables are being set and I think build.rs is a good place to keep that info.

**Comment by netrome** [comment]
> This all looks good though I would like to see the body of main() remain as it shows what env variables are being set and I think build.rs is a good place to keep that info.

Fair point, I was already a bit torn whether to factor out the contents of main or not. I'll update :)

**Comment by netrome** [comment]
Done! Amended the commit to keep the history clean.

**Review by donpdonp — APPROVED** [review]
thats awesome. thanks.

**Pull request merged**
